INSERT INTO public.measurement_rule_code (id, category, section, label, code)
VALUES
  (uuid_generate_v4(), '상의', '몸통', '어깨 너비', 'BODY_SHOULDER_WIDTH'),
  (uuid_generate_v4(), '상의', '몸통', '진동 너비', 'BODY_ARM_HOLE_WIDTH'),
  (uuid_generate_v4(), '상의', '몸통', '가슴 너비', 'BODY_CHEST_WIDTH'),
  (uuid_generate_v4(), '상의', '몸통', '허리 너비', 'BODY_WAIST_WIDTH'),
  (uuid_generate_v4(), '상의', '몸통', '진동하단 너비', 'BODY_UNDER_ARM_HOLE_WIDTH'),
  (uuid_generate_v4(), '상의', '몸통', '목 둘레', 'BODY_NECK_CIRCUMFERENCE'),
  (uuid_generate_v4(), '상의', '몸통', '가슴 둘레', 'BODY_CHEST_CIRCUMFERENCE'),
  (uuid_generate_v4(), '상의', '몸통', '전체 길이', 'BODY_TOTAL_LENGTH'),
  (uuid_generate_v4(), '상의', '몸통', '어깨경사 길이', 'BODY_SHOULDER_SLOPE_LENGTH'),
  (uuid_generate_v4(), '상의', '몸통', '앞목 길이', 'BODY_FRONT_NECK_LENGTH'),
  (uuid_generate_v4(), '상의', '몸통', '뒷목 길이', 'BODY_BACK_NECK_LENGTH'),
  (uuid_generate_v4(), '상의', '몸통', '진동 길이', 'BODY_ARM_HOLE_LENGTH'),
  (uuid_generate_v4(), '상의', '몸통', '앞진동 길이', 'BODY_FRONT_ARM_HOLE_LENGTH'),
  (uuid_generate_v4(), '상의', '몸통', '뒤진동 길이', 'BODY_BACK_ARM_HOLE_LENGTH'),
  (uuid_generate_v4(), '상의', '몸통', '허리 길이', 'BODY_WAIST_LENGTH'),
  (uuid_generate_v4(), '상의', '몸통', '래글런 길이', 'BODY_RAGLAN_LENGTH'),
  (uuid_generate_v4(), '상의', '몸통', '고무단 길이', 'BODY_BOTTOM_BAND_LENGTH'),
  (uuid_generate_v4(), '상의', '몸통', '어깨경사 너비', 'BODY_SHOULDER_SLOPE_WIDTH'),
  (uuid_generate_v4(), '상의', '몸통', '앞목 너비', 'BODY_FRONT_NECK_WIDTH'),
  (uuid_generate_v4(), '상의', '몸통', '뒷목 너비', 'BODY_BACK_NECK_WIDTH'),
  (uuid_generate_v4(), '상의', '몸통', '고무단 너비', 'BODY_BOTTOM_BAND_WIDTH'),
  (uuid_generate_v4(), '상의', '몸통', '앞목 둘레', 'BODY_FRONT_NECK_CIRCUMFERENCE'),
  (uuid_generate_v4(), '상의', '몸통', '뒷목 둘레', 'BODY_BACK_NECK_CIRCUMFERENCE'),
  (uuid_generate_v4(), '상의', '몸통', '넥밴드 길이', 'BODY_NECK_BAND_LENGTH'),
  (uuid_generate_v4(), '상의', '소매', '소매산 길이', 'SLEEVE_SLEEVE_CAP_LENGTH'),
  (uuid_generate_v4(), '상의', '소매', '소매 앞진동 길이', 'SLEEVE_FRONT_ARM_HOLE_LENGTH'),
  (uuid_generate_v4(), '상의', '소매', '소매 뒤진동 길이', 'SLEEVE_BACK_ARM_HOLE_LENGTH'),
  (uuid_generate_v4(), '상의', '소매', '소매 래글런 길이', 'SLEEVE_RAGLAN_LENGTH'),
  (uuid_generate_v4(), '상의', '소매', '소매 고무단 길이', 'SLEEVE_BOTTOM_BAND_LENGTH'),
  (uuid_generate_v4(), '상의', '소매', '소매산 너비', 'SLEEVE_SLEEVE_CAP_WIDTH'),
  (uuid_generate_v4(), '상의', '소매', '소매 고무단 너비', 'SLEEVE_BOTTOM_BAND_WIDTH'),
  (uuid_generate_v4(), '상의', '소매', '소매 어깨 둘레', 'SLEEVE_SHOULDER_CIRCUMFERENCE'),
  (uuid_generate_v4(), '상의', '소매', '소매 너비', 'SLEEVE_TOTAL_WIDTH'),
  (uuid_generate_v4(), '상의', '소매', '소매 길이', 'SLEEVE_TOTAL_LENGTH');